### PR TITLE
Moved graphql to a peer-dependency

### PR DESCRIPTION
**Pull request by Siyfion**
Also updated the dependency to the latest release of `graphql`.

### CODE REVIEW

**Comment by helfer** [comment]
I think with npm 3 you also have to make it a devDependency to make sure it gets installed for the tests.

**Comment by Siyfion** [comment]
That would explain why one environment fails and the other succeeds!

**Comment by Siyfion** [comment]
@helfer There you go, that should do it 👍

**Comment by helfer** [comment]
@Siyfion can we make the peer dependency accept a range like in graphql-tools? That way this change can be completely non-breaking.

**Comment by Siyfion** [comment]
@helfer Shall I leave the minimum on 0.7.x (previous dependency) or .5 / .6 like `graphql-tools`?

**Comment by helfer** [comment]
Minimum should be what we had before, because I don't know if it will work with 0.6

**Comment by Siyfion** [comment]
Ah okay... `0.7.0` minimum it is!

**Comment by helfer** [comment]
@Siyfion thanks, awesome! I'll release a new version in the next few hours.

**Comment by helfer** [comment]
nvm, I already published it 😁

**Comment by Siyfion** [comment]
Awesome! Thanks for the help @helfer!

**Comment by Urigo** [comment]
https://github.com/apollostack/graphql-subscriptions/issues/23

**Comment by dotansimha** [comment]
Awesome!! Thanks!!

**Pull request merged**
